### ISSUE TITLE
fedora instance not accessible outside DomsEventStorage.

### ISSUE THREAD

**Issue by ravn** [statsbiblioteket/newspaper-batch-event-framework#1]
dk.statsbiblioteket.medieplatform.autonomous.DomsEventStorage
needs a getter for the fedora field for DPA.

**Comment by kaarefc** [comment]
That seems like a serious breach of encapsulation.
Why does DPA need direct access to the Fedora instance?

**Comment by ravn** [comment]
Perhaps we need a specific call to modifyDatastreamByValue(...) not exposed by current API.  Lets discuss.

**Comment by ravn** [comment]
Problem is we in DPA want to save a datastream for a specific domsID (to save output from VeraPDF and others).  We need the "official way" to do this which is outside the scope of DomsEventStorage so closing issue.
